config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, reverse_lazy, include


urlpatterns = [
    path('', include("sales_prediction.apps.base.urls")),
    path('admin-panel/', admin.site.urls),
    
]


# Media and Static files for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales_prediction/apps/base/urls.py
from django.urls import path

from . import views

app_name = "base"

urlpatterns = [
    path('', views.HomePageView.as_view(), name="home-page"),
]

sales_prediction/apps/base/models.py
from django.db import models

# Create your models here.

sales_prediction/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _



class User(AbstractUser):
    username = models.CharField(max_length=150, blank=True, null=True)
    email = models.EmailField(
        _('Email Address'), 
        unique=True, 
        error_messages={
            'unique': _("Already an account exists with this email."),
        })
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __str__(self):
        return self.email

sales_prediction/apps/base/views.py
from django.shortcuts import render

from django.views.generic.base import TemplateView
# Create your views here.

class HomePageView(TemplateView):
    template_name = "base/home.html"

sales_prediction/apps/user/views.py
from django.shortcuts import render

# Create your views here.

sales_prediction/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="{% block meta_description %}{% endblock meta_description %}">

    <title>{% block title %}{% endblock title %}</title>

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" 
    rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


    {# Vendor CSS #}
    <link rel="stylesheet" href="{% static 'vendor/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/mdb.min.css' %}">

    {# Custom CSS #}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    {% block head %}
    {% endblock head %}
</head>
<body>
    <div class="container-fluid px-0">
        {% block navigation %}
            {% include "navigation.html" %}

        {% endblock navigation %}

        {% block content %}
        {% endblock content %}

        {% block footer %}
            {% include "footer.html" %}
        {% endblock footer %}
    </div>
    <!-- Notify message     -->
    {% if messages %}
        <script>
        $(document).ready(function() {
            {% for message in messages %}
                
                $.notify({
                    // options
                    message: "{{message}}"
                },{
                    // settings
                    type: "{{message.tags}}"
                });
            {% endfor %}
        });
        </script>
    {% endif %}
    
     <!-- Vendor's JS-->
    <!-- JQuery js -->
    <script src="{% static 'vendor/js/jquery.min.js' %}"></script>
    <!-- Popper Js -->
    <script src="{% static 'vendor/js/popper.js' %}"></script>
    <!-- Notify Js -->
    <script src="{% static 'vendor/js/bootstrap-notify/bootstrap-notify.min.js' %}"></script>
    <!-- Bootstrap Js -->
    <script src="{% static 'vendor/js/bootstrap.js' %}"></script>
    <!-- Material Design Js -->
    <script src="{% static 'vendor/js/mdb.min.js' %}"></script>

    {# Custom JS #}
    <script src="{% static 'js/global.js' %}"></script>

</body>
</html>

sales_prediction/templates/base/home.html
{% extends "base.html" %}
{% load static %}

{% block meta_description %}{{ meta_description }}{% endblock meta_description %}
{% block title %} {{ page_title }} {% endblock title %}

{% block content %}


<div class="row">
    <div class="col-12 text-center">
        <h1> Home Page</h1>
    </div>
</div>
{% endblock content %}

sales_prediction/templates/footer.html
{% load static %}
<footer class="page-footer font-small">
    <div class="container-fluid footer-copyright py-3">
        <div class="row">

            <div class="col-12 col-md-12">
                <div class="text-center">
                    © 2018-19 Copyright: <a href="#"> Company Name</a>
                </div>
            </div>
            <!-- <div class="col-12 col-sm-4">
                <div class="text-center">
                    Payment Support: <img src="{% static 'bca_logo.png' %}" alt="Logo">
                </div>
            </div> -->
            {% comment %} <div class="col-12 col-sm-4">
                <div class="text-right">
                    <small>Developed by <a href="#"> Invento Bangladesh</a></small>
                </div>
            </div> {% endcomment %}
        </div>
        
    </div>
</footer>

sales_prediction/templates/navigation.html
{% load i18n static %}

<nav class="navbar navbar-expand-lg  navbar-light">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'base:home-page'%} ">
                Company Name
            </a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">

            <ul class="navbar-nav m-auto mt-1 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'base:home-page'%} ">{% trans 'HOME' %}</a>
                        
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#">{% trans 'ABOUT' %}</a>
                    </li>

            </ul>
            <ul class="navbar-nav float-md-right mt-1 mt-lg-0">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">{% trans 'LOGOUT' %}</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="#">{% trans 'LOGIN' %}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>